# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: PowerShell@2
  displayName: 'PSAnalyzer for scripts'
  inputs:
    filePath: 'AADGuestUser/ci/scripts/PSAnalyzer.ps1'
    workingDirectory: 'AADGuestUser/ci/scripts'
- task: PowerShell@2
  displayName: 'Run Pester Tests for Send script'
  inputs:
    filePath: 'AADGuestUser/ci/scripts/Pester.ps1'
    workingDirectory: 'AADGuestUser/ci/scripts'



