---
name: Test and run PSScriptAnalyzer
on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  pester-test:
    name: Pester test
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Test and run PSScriptAnalyzer
      shell: pwsh
      run: |
        ./build.ps1
